<?php
  include_once('./inc/header.php');
?>
<div class="container mt-5">
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th>代码</th>
        <th>中文名</th>
        <th>英文名</th>
        <th>默认重量单位</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>AU</th>
        <td>澳大利亚</td>
        <td>Australia</td>
        <td>KG</td>
      </tr>
      <tr>
        <th>KR</th>
        <td>韩国</td>
        <td>Korea, Rep.</td>
        <td></td>
      </tr>
      <tr>
        <th>IN</th>
        <td>印度</td>
        <td>India</td>
        <td></td>
      </tr>
      <tr>
        <th>IT</th>
        <td>意大利</td>
        <td>Italy</td>
        <td></td>
      </tr>
      <tr>
        <th>MY</th>
        <td>马来西亚</td>
        <td>Malaysia</td>
        <td>KG</td>
      </tr>
      <tr>
        <th>FR</th>
        <td>法国</td>
        <td>France</td>
        <td></td>
      </tr>
      <tr>
        <th>TW</th>
        <td>台湾</td>
        <td>NULL</td>
        <td>KG</td>
      </tr>
      <tr>
        <th>AU</th>
        <td>澳大利亚</td>
        <td>Australia</td>
        <td>KG</td>
      </tr>
      <tr>
        <th>JP</th>
        <td>日本</td>
        <td>Japan</td>
        <td></td>
      </tr>
      <tr>
        <th>NZ</th>
        <td>新西兰</td>
        <td>New Zealand</td>
        <td></td>
      </tr>
      <tr>
        <th>HK</th>
        <td>香港</td>
        <td>Hong Kong</td>
        <td>KG</td>
      </tr>
      <tr>
        <th>GB</th>
        <td>英国</td>
        <td>United Kingdom</td>
        <td></td>
      </tr>
      <tr>
        <th>DE</th>
        <td>德国</td>
        <td>Germany</td>
        <td></td>
      </tr>
      <tr>
        <th>VN</th>
        <td>越南</td>
        <td>Viet Nam</td>
        <td></td>
      </tr>
      <tr>
        <th>CN</th>
        <td>中国内地</td>
        <td>China</td>
        <td></td>
      </tr>
      <tr>
        <th>CA</th>
        <td>加拿大</td>
        <td>Canada</td>
        <td>LB</td>
      </tr>
      <tr>
        <th>SG</th>
        <td>新加坡</td>
        <td>Singapore</td>
        <td></td>
      </tr>
      <tr>
        <th>US</th>
        <td>美国</td>
        <td>United States</td>
        <td>LB</td>
      </tr>
      <tr>
        <th>ES</th>
        <td>西班牙</td>
        <td>Spain</td>
        <td></td>
      </tr>
    </tbody>
  </table>
</div>
<?php
  include_once('./inc/footer.php');
?>
