<?php include_once('./inc/header.php') ?>
    <div class="container mt-5">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th>代码</th>
            <th>解释</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>PU</th>
            <td>货物已从发件人处提取</td>
          </tr>
          <tr>
            <th>CL</th>
            <td>站点揽收</td>
          </tr>
          <tr>
            <th>AO</th>
            <td>到达海外仓库</td>
          </tr>
          <tr>
            <th>OC</th>
            <td>操作完成</td>
          </tr>
          <tr>
            <th>LO</th>
            <td>离开海外仓库</td>
          </tr>
          <tr>
            <th>FT</th>
            <td>航班起飞</td>
          </tr>
          <tr>
            <th>FL</th>
            <td>航班降落</td>
          </tr>
          <tr>
            <th>KRW</th>
            <td>韩元</td>
          </tr>
          <tr>
            <th>TRM</th>
            <td>正在送往清关口岸</td>
          </tr>
          <tr>
            <th>CCE</th>
            <td>已清关完成</td>
          </tr>
          <tr>
            <th>OK</th>
            <td>货物已经派送</td>
          </tr>
          <tr>
            <th>CP</th>
            <td>货物正在清关，等候海关放行</td>
          </tr>
          <tr>
            <th>CCMC</th>
            <td>货物已经遗失</td>
          </tr>
          <tr>
            <th>CCSD</th>
            <td>货物已经被销毁</td>
          </tr>
          <tr>
            <th>IDCS</th>
            <td>身份证信息收集</td>
          </tr>
          <tr>
            <th>IS</th>
            <td>已交接国内派送服务商</td>
          </tr>
          <tr>
            <th>PL</th>
            <td>作业中心内部操作</td>
          </tr>
          <tr>
            <th>PO</th>
            <td>海外仓库打单</td>
          </tr>
          <tr>
            <th>RT</th>
            <td>货物已退回发件地</td>
          </tr>
          <tr>
            <th>SD</th>
            <td>货物破损</td>
          </tr>
          <tr>
            <th>SH</th>
            <td>货物暂扣</td>
          </tr>
          <tr>
            <th>HC</th>
            <td>海关扣件</td>
          </tr>
          <tr>
            <th>TRM</th>
            <td>正在送往清关口岸</td>
          </tr>
          <tr>
            <th>PTW</th>
            <td>包裹从机场提取，转往海关监管仓</td>
          </tr>
          <tr>
            <th>WA</th>
            <td>等待安排航班</td>
          </tr>
          <tr>
            <th>WT</th>
            <td>等待安排转关</td>
          </tr>
          <tr>
            <th>WD</th>
            <td>等待清关</td>
          </tr>
          <tr>
            <th>OK</th>
            <td>派送完成</td>
          </tr>
        </tbody>
      </table>
    </div>

<?php include_once('./inc/footer.php') ?>

